services:
  backend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:nischalpaliwal7@postgres:5432/monorepo
    depends_on:
      - postgres
  frontend:
    build:
      context: ./
      dockerfile: docker/Dockerfile.frontend
      args:
        - DB_URL=postgresql://postgres:nischalpaliwal7@postgres:5432/monorepo
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:nischalpaliwal7@postgres:5432/monorepo
    depends_on:
      - postgres
  ws:
    build:
      context: ./
      dockerfile: docker/Dockerfile.ws
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:nischalpaliwal7@postgres:5432/monorepo
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=nischalpaliwal7
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: